AWSTemplateFormatVersion: '2010-09-09'
Description: Setting up your own private and secure VPN. You can read instructions
  on our blog https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/
  and you can follow video instructions on Youtube https://www.youtube.com/watch?v=fBBERp5CUgo

Parameters:
  Username:
    Description: VPN Username
    Type: String
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  VPNPassword:
    NoEcho: 'true'
    Description: VPN Password (Min 4 characters)
    Type: String
    MinLength: '4'
    MaxLength: '255'
    ConstraintDescription: must contain atleast 4 characters.
  VPNPhrase:
    NoEcho: 'true'
    Description: Passphrase for IPSEC PSK (Min 4 characters)
    Type: String
    MinLength: '4'
    MaxLength: '255'
    ConstraintDescription: must contain atleast 4 characters.
  Size:
    Description: Instance Type
    Type: String
    Default: Standard.VPN-t2.micro
    AllowedValues:
    - Standard.VPN-t2.micro
    - High.Speed.VPN-t3.micro
    - Ultra.High.Speed.VPN-t3.medium

Mappings:
  AWSInstanceType2Arch:
    Standard.VPN-t2.micro:
      InstanceType: t2.micro
    High.Speed.VPN-t3.micro:
      InstanceType: t3.micro
    Ultra.High.Speed.VPN-t3.medium:
      InstanceType: t3.medium
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0b0dcb5067f052a63
    us-east-2:
      HVM64: ami-0beaa649c482330f7
    us-west-1:
      HVM64: ami-0f5e8a042c8bfcd5e
    us-west-2:
      HVM64: ami-094125af156557ca2
    af-south-1:
      HVM64: ami-0f4500c7ee9bc5381
    ap-east-1:
      HVM64: ami-0a2dce9a0bf96fdb3
    ap-south-2:
      HVM64: ami-0049db3e0caaf7855
    ap-southeast-3:
      HVM64: ami-0dbbdadea5c056087
    ap-south-1:
      HVM64: ami-074dc0a6f6c764218
    ap-northeast-3:
      HVM64: ami-0e0cbf0f03ba99ee7
    ap-northeast-2:
      HVM64: ami-0eddbd81024d3fbdd
    ap-southeast-1:
      HVM64: ami-0af2f764c580cc1f9
    ap-southeast-2:
      HVM64: ami-06bb074d1e196d0d4
    ap-northeast-1:
      HVM64: ami-072bfb8ae2c884cc4
    ca-central-1:
      HVM64: ami-0ee679ef733e3b8e7
    eu-central-1:
      HVM64: ami-076309742d466ad69
    eu-west-1:
      HVM64: ami-01cae1550c0adea9c
    eu-west-2:
      HVM64: ami-04706e771f950937f
    eu-south-1:
      HVM64: ami-03a68febd9b9a5403
    eu-west-3:
      HVM64: ami-0f15e0a4c8d3ee5fe
    eu-south-2:
      HVM64: ami-0114de0ad847da090
    eu-north-1:
      HVM64: ami-02aeff1a953c5c2ff
    eu-central-2:
      HVM64: ami-0b0ef1576c8aba3ed
    me-south-1:
      HVM64: ami-06615079e3e6ae80e
    me-central-1:
      HVM64: ami-045fe36905963969b
    sa-east-1:
      HVM64: ami-0b7101e993ea27f3a

Resources:
  VPNServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - HVM64
      InstanceType:
        Fn::FindInMap:
        - AWSInstanceType2Arch
        - Ref: Size
        - InstanceType
      SecurityGroups:
      - Ref: VPNSecurityGroup
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/sh
            #Passing variables to shell
            YOUR_IPSEC_PSK=${VPNPhrase}
            YOUR_USERNAME=${Username}
            YOUR_PASSWORD=${VPNPassword}
            #VPN - L2TP IPSEC Server
            wget https://get.vpnsetup.net -O vpnsetup.sh && sudo \
            VPN_IPSEC_PSK=$YOUR_IPSEC_PSK \
            VPN_USER=$YOUR_USERNAME \
            VPN_PASSWORD=$YOUR_PASSWORD sh vpnsetup.sh

  VPNSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPN Security Groups
      SecurityGroupIngress:
      - IpProtocol: udp
        FromPort: '500'
        ToPort: '500'
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: '4500'
        ToPort: '4500'
        CidrIp: 0.0.0.0/0
Outputs:
  VPNServerAddress:
    Description: Use the IP as Server Address or VPN Host
    Value:
      Fn::GetAtt:
        - VPNServerInstance
        - PublicIp
  WebdigiNotes:
    Description: Allow upto 5 minutes after setup to connect. Please contact us at
      https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/
      for any help!
    Value: Comments
